manifest: "v1"

# Events are grouped every <interval> for deduplication purposes
interval: 1000

# Pod specific configuration
pod:
  cwd: "/app"

watch:
  - pattern: "./[^node_modules]/**/*.{js,css,img,html,vue,ts}"
  - pattern: "./**/*.php"
  - pattern: "*.go"
